parameters:
    database_driver:   pdo_mysql
    database_host:     devcreek
    database_port:     ~
    database_name:     jt_test_dc
    database_user:     jaume.tarradas
    database_password: P455w0rd

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt