parameters:
#    bic_enllac.example.class: Bic\EnllacBundle\Example

services:
#    bic_enllac.example:
#        class: %bic_enllac.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
